### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by MFTTech** [Microsoft/SmartHotel360-Website#1]
Got the warnings below:

> npm WARN engine extract-text-webpack-plugin@2.1.2: wanted: {"node":">=4.3.0 < 5.0.0 || >= 5.10"} (current: {"node":"5.4.1","npm":"3.3.4"})
> npm WARN engine webpack@2.5.1: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"5.4.1","npm":"3.3.4"})
> npm WARN deprecated @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
> npm WARN engine sass-loader@6.0.6: wanted: {"node":">= 4.3 < 5.0.0 || >= 5.10"} (current: {"node":"5.4.1","npm":"3.3.4"})
> npm WARN engine enhanced-resolve@3.4.1: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"5.4.1","npm":"3.3.4"})
> npm WARN engine schema-utils@0.3.0: wanted: {"node":">= 4.3 < 5.0.0 || >= 5.10"} (current: {"node":"5.4.1","npm":"3.3.4"})
> npm WARN engine loader-runner@2.3.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"5.4.1","npm":"3.3.4"})
> npm WARN install Couldn't install optional dependency: Unsupported
> npm WARN prefer global node-gyp@3.6.2 should be installed with -g

Not sure if related to error I get when I build solution:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Missing binding C:\Git\Source\Repos\SmartHotel360-public-web\SmartHotel360.PublicWeb\node_modules\node-sass\vendor\win32-x64-57\binding.node	SmartHotel360.PublicWeb	C:\Git\Source\Repos\SmartHotel360-public-web\SmartHotel360.PublicWeb\Module build failed	1

**Comment by eiximenis** [comment]
Hi, the warnings are not related to error.

Try to run  `npm rebuild node-sass` from the command line (located in the same folder as `package.json` file. This will rebuild a node-sass binary for your architecture.
Then you should be able to compile the web.

**Comment by npagare** [comment]
Hi Eximenis, I followed those steps, but that issue still persists. Any thoughts ?

![image](https://user-images.githubusercontent.com/26844611/34965459-c6f407f4-fa19-11e7-96fb-3077cdcbc68c.png)

![image](https://user-images.githubusercontent.com/26844611/34965445-b4b55ca0-fa19-11e7-9845-18c70466a01b.png)

Thanks

**Comment by eiximenis** [comment]
Hi. Seems that node-saas is not supported in your environment. 

Which nodejs are you using? [In this issue](https://github.com/jakearchibald/wittr/issues/20) have some clues about how this can be solved...

**Comment by npagare** [comment]
Hi, 
I am using nodejs on windows ... vesion 9.3 and npm version 5.5.1
Screenshot below -

![image](https://user-images.githubusercontent.com/26844611/35000479-2141fc1c-faaa-11e7-9055-b46f9663a9b4.png)

**Comment by npagare** [comment]
Hi eiximenis, any thoughts based on input? 
Thanks

**Comment by eiximenis** [comment]
Hi @IoTFier,
I think is related about node 9 (never tested with that version of node).

Here is an [issue about node-sass and node 9](https://github.com/sass/node-sass/issues/2129).  We are using node-sass 4.5.3 and seems that node 9 is supported only in 4.6 and above.
Could you try to update node-sass package (`npm update node-sass`) to see if it helps with your issue?

**Comment by npagare** [comment]
Hi eiximenis, I tried executing npm update node-sass. Here are some results..
![image](https://user-images.githubusercontent.com/26844611/35188899-025cc738-fe05-11e7-9639-b82552bd92fe.png)
After that I rebuilt the public web solution and running F5 threw the same error as above 
![image](https://user-images.githubusercontent.com/26844611/35188914-55806cee-fe05-11e7-9108-072de9def546.png)
After this error, I again tried to rebuild the node-sass module. The rebuild command didn't throw any error; but running the public web app showed the same error as above.

Any thoughts ? 
-Thanks

**Comment by bradygmsft** [comment]
@IoTFier - the node-sass package relies on Python. Do you have it installed? If that doesn't resolve it for you, there's also [this](https://www.npmjs.com/package/windows-build-tools) NPM package, which might help unblock when doing NPM builds on your Windows machine.

**Comment by npagare** [comment]
hello @bradygmsft , I have python installed as a part of the Visual Studio installation.

**Comment by bradygmsft** [comment]
@IoTFier thanks for that info - are you still blocked by this?

**Comment by fpelaez** [comment]
Hi @IoTFier ,
Looking at your screenshots you are running "npm rebuild node-sass" on the wrong folder, could you try to run the command on the folder  C:\XFDev\SmartHotel360-public-web\SmartHotel360.PublicWeb\ instead of the folder C:\XFDev\SmartHotel360-public-web\SmartHotel360.PublicWeb\node_modules.

If that doesn't work you can check if you have Python on the PATH.

An alternative is to open a command line with administrative rights and run "npm --add-python-to-path='true' --debug install --global windows-build-tools", then open a command line, navigate to the project folder, in your case C:\XFDev\SmartHotel360-public-web\SmartHotel360.PublicWeb\ then run "npm rebuild node-sass" and finally restart VS

Hope this works

**Comment by npagare** [comment]
Hi @fpelaez , I followed your guidance and still facing the same issue.

![image](https://user-images.githubusercontent.com/26844611/35588084-353eec40-05c5-11e8-85c6-f69499768fa8.png)

I am executing the command  run "npm --add-python-to-path='true' --debug install --global windows-build-tools" as I update my comment. The execution seems like hung at teh step "waiting for the installers .... " for quite sometime. **My curiosity is why this step is needed when I already had python version 2.7.14 installed at global level?** I see the above command just finished installing an older version from python-2.7.13.msi

![image](https://user-images.githubusercontent.com/26844611/35588214-83a28d7e-05c5-11e8-8870-b5b4daab1062.png)

running npm rebuild node0sass still fails as npm is still not able to find the some file (don't know which one)
![image](https://user-images.githubusercontent.com/26844611/35588283-c1234076-05c5-11e8-8ff2-4c6e56bfebdc.png)

I appreciate your help. 
Thanks,

**Comment by srivatsamarichi** [comment]
@eiximenis I have the same problem running public web on my machine too. node version=6.10.2, npm=5.6.0.
![sh360_public_web_error](https://user-images.githubusercontent.com/13433045/35665180-ee635c48-074a-11e8-8eb9-92a008e13b5b.png)

**Comment by eiximenis** [comment]
This is a nightmare :S
Not sure how I can help, so **I created a Dockerfile and a Compose file to build & run the web using Docker**. If you have Docker installed (Linux containers only), only need to go where the `docker-compose.yml` file is and from any command prompt type:

```
docker-compose up
```
This will build and start the web using Docker. The  output should be something like:
```
E:\C2017\SmartHotel360-public-web>docker-compose up
Recreating smarthotel360publicweb_smarthotel360.publicweb_1 ... done
Attaching to smarthotel360publicweb_smarthotel360.publicweb_1
smarthotel360.publicweb_1  | info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
smarthotel360.publicweb_1  |       User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
smarthotel360.publicweb_1  | info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
smarthotel360.publicweb_1  |       Creating key {d750e653-90c1-49e4-97ea-c802b071dd91} with creation date 2018-02-02 16:48:36Z, activation date 2018-02-02 16:48:36Z, and expiration date 2018-05-03 16:48:36Z.
smarthotel360.publicweb_1  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
smarthotel360.publicweb_1  |       No XML encryptor configured. Key {d750e653-90c1-49e4-97ea-c802b071dd91} may be persisted to storage in unencrypted form.
smarthotel360.publicweb_1  | info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
smarthotel360.publicweb_1  |       Writing data to file '/root/.aspnet/DataProtection-Keys/key-d750e653-90c1-49e4-97ea-c802b071dd91.xml'.
smarthotel360.publicweb_1  | Hosting environment: Production
smarthotel360.publicweb_1  | Content root path: /app
smarthotel360.publicweb_1  | Now listening on: http://[::]:80
smarthotel360.publicweb_1  | Application started. Press Ctrl+C to shut down.
```
Once web is started, just open another command prompt and type:
```
docker ps --filter ancestor=smarthotel360.publicweb
```
Output will be the running container with the web:
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                   NAMES
c081184dd954        smarthotel360.publicweb   "dotnet SmartHotel36…"   4 minutes ago       Up 4 minutes        0.0.0.0:32778->80/tcp   smarthotel360publicweb_smarthotel360.publicweb_1
```
Note the `PORTS` column, with the address `0.0.0.0:32778`. This is the port where you can find the web. So, just go to `http://localhost:32778` and the pubic web should appear. **Note that this port could change any time you start the web using `docker-compose up`**.

To stop the container just type `docker-compose down` on any command prompt located at the same folder where `docker-compose.yml` file is.

Hope this helps!

PS: Commit is 59e3d4ec50562158ff9f47354f9d522a8d3f7a9d and its on master branch right now.

**Comment by srivatsamarichi** [comment]
@eiximenis @bradygmsft Also this is a SPA? I cannot login nor do bookings etc.. I have all my required backend services hosted on Azure.

**Comment by npagare** [comment]
Hi @eiximenis ,
docker-compose up causing build of the web app resulted in the following error. 
Thoughts ? 

I understand even you feel frustrated but that's what this community and Xamarin team need to understand from our perspective. If the initial bootstrap of setting up these apps takes so much time and effort, then, definitely something is not being done right. Either the documentation is not outlining things well enough or we are doing too many things between IDE and command prompt; third party dependency and mess caused by too many software version conflicts.

Please note - we truly appreciate the intent and effort put in to build this reference app. It is awesome! But there are lots of issues that is breaking confidence and pulling many of us away from learning the core technology itself.

![image](https://user-images.githubusercontent.com/26844611/36350571-3f1a9b0c-1460-11e8-9d40-1119b46a9e1a.png)

Thanks

**Comment by eiximenis** [comment]
Hi @IoTFier 

I tested in a Windows 10 with Docker CE For Windows (18.02.0-ce-win52 (15732)) and it worked for me with no issues.

With versions do you have (OS & Docker)?

**Comment by npagare** [comment]
Hi @eiximenis,

My OS version is Win 10 Pro 64 bit with the latest Feb security update.
Docker version 17.12.0-ce, build c97c6d6 [ I am not running edge release]

Thanks

**Comment by srivatsamarichi** [comment]
@bradygmsft Thanks a lot for the [workaround](https://www.npmjs.com/package/windows-build-tools). It helped and works fine now. 

@IoTFier Please do try the above mentioned workaround, it should work as expected. Below is the screenshot after successfull installation of Python packages for your reference.

![installing_python_tools](https://user-images.githubusercontent.com/13433045/37516511-5ea05d70-2934-11e8-9bda-128fa3d9bddd.png)

@eiximenis The docker build is still failing. Can you please help us here?

Thanks

**Comment by bradygmsft** [comment]
@SrivatsaMarichi regarding your docker question, there's no docker in the public web demo.

**Comment by srivatsamarichi** [comment]
@bradygmsft Since the public web was failing due to node issues @eiximenis created a docker supported project. Hence tried with the same.

**Comment by bradygmsft** [comment]
I see that now, @SrivatsaMarichi. Question to @IoTFier - were you ever able to move past this issue? The node-sass issue is something @eiximenis and i have talked about with some of our peers and the complexities of building the node-sass dependencies are just the nature of node-sass. I don't mean to diminish the frustration at all (trust me! we wish this part could be easier!) I'd be open to suggestions or alternatives here. 

Would using LESS be an option the community would accept?
