### ISSUE TITLE
public endpoints not reachable

### ISSUE THREAD

**Issue by gerrieswart** [Microsoft/SmartHotel360-Website#11]
It seems the default public endpoints in the appsetting.json is not reachable .
sh360services-public.eastus2.cloudapp.azure.com

Can't be reached..

**Comment by bradygaster** [comment]
Thanks for that report, @gerrieswart - i am in the process of rebuilding our production environment now. Once I do, I will update the public endpoint configuration in the public web app and post an update to this issue. Apologies - we just started the update of our back-end hosting environment to AKS and will get it done ASAP.

**Comment by Saravanan109587** [comment]
Can I get Backend to host in my local system, If Can where I can find that,Can you please suggest me

**Comment by bradygmsft** [comment]
@gerrieswart and @Saravanan109587 - this repo has been updated with our public endpoints. thanks for letting us know about this, and apologies for the delay.
