### ISSUE TITLE
Documents are not created in Azure Cosmos DB

### ISSUE THREAD

**Issue by srivatsamarichi** [Microsoft/SmartHotel360-Website#2]
My configuration is correct. I cannot see the documents in a collection called checks in a database pets!

**Comment by bradygmsft** [comment]
@SrivatsaMarichi are you running the app locally or in Azure? Did you F5 the public web app project *and* the Function project? Thanks for providing a little more information so we can help troubleshoot.

**Comment by srivatsamarichi** [comment]
@bradygmsft I am running locally. I F5'd the **PetChecker** app as I had issues running the web. [Issue](https://github.com/Microsoft/SmartHotel360-public-web/issues/1) is logged here for the web.

**Comment by bradygmsft** [comment]
@SrivatsaMarichi did you configure the local settings file in the function project and also the one in the web project?

**Comment by srivatsamarichi** [comment]
@bradygmsft Yes I did.

**Comment by bradygmsft** [comment]
[moved to here](https://github.com/Microsoft/SmartHotel360-Sentiment-Analysis-App/issues/3)
