### ISSUE TITLE
Pet checking is not working - pet image not uploaded

### ISSUE THREAD

**Issue by harrchen88** [Microsoft/SmartHotel360-Website#28]
I am running both web site and function locally.  They started fine and I can find hotels.  However, when trying the pet check, the image uploading is not working - nothing happens after the pet image is selected.  
I have node.js V8.9.4 installed on my Surface Book with VS 2017 V15.9.10 installed.
I followed the demo script for the steps.
Appreciate any help.  Below is my appsetting.development.json file (replaced letters):
"PetsConfig": {
    "blobName": "myblobxxxforsmarthotel",
    "blobKey": "abcdefgnnnnnn==",
    "cosmosUri": "https://mytestxxxsmarthotelcosmo.documents.azure.com:443/",
    "cosmosKey": "abceefgxxxxx==",
    "api": "http://petchecker.azurewebsites.net"
  },

**Comment by ivilches** [comment]
Hello! You must include the "allow all origins" setting in the function's local.setings.json file:
  ....
 "FUNCTIONS_WORKER_RUNTIME": "dotnet"
},
**"Host": {
    "CORS": "*"
  }**
.....
It's needed for the function to accept OPTIONS requests; I've sent a [Pull Request](https://github.com/microsoft/SmartHotel360-Website/pull/31) solving this issue. 
Anyway, in your appsettings.Development.json it seems you're setting a deployed azure function's uri, not a local.
