### ISSUE TITLE
No unit tests?

### ISSUE THREAD

**Issue by dziedrius** [Microsoft/SmartHotel360-Website#3]
As long as this is a reference project, it would be interesting to see how testing infrastructure is set up (backend and frontend).

**Comment by bradygmsft** [comment]
@dziedrius this is a good suggestion. To be transparent, the solution represented in these repos began as a demo series. Demo series are sometimes built pretty early, and pretty quickly, and tests aren't always something for which we have the luxury to implement. That's not to imply that TDD has any negative impact on the speed at which a project can be completed, and I'm a huge advocate of testing whenever and wherever possible. I think adding some basic tests to demonstrate how the devops features could be used to ensure quality and stability, but I don't think we'd implement the absolute full battery of tests on SmartHotel360 that we'd all aspire to have in production code. 

What areas would you like to see prioritized in terms of tests? Any components in the demo series you feel would lend well to demonstrating implementing tests to validate success? I'd be open to ideas and collaboration here.

**Comment by dziedrius** [comment]
To me personally testing client side is the most interesting part at the moment, as there's no well defined way how to integrate that with Visual Studio workflow. Currently we're using mocha+karma+task runner explorer, but that was not straightforward to set up and has it's downsides.

So I guess if we would start from testing react components, that would be very interesting thing to follow.

**Comment by dsanchezcr** [comment]
Closing this issue since we are not adding more features to this app.
