### ISSUE TITLE
Images are not stored in a blob container

### ISSUE THREAD

**Issue by srivatsamarichi** [Microsoft/SmartHotel360-Website#5]
@bradygmsft When I run Azure function locally, the images should store in a blob container and create documents in CosmosDB according to the guide. Instead it isn't creating one. Can you help me out here?

**Comment by bradygmsft** [comment]
What is it not creating? Are the images landing in the storage account?

**Comment by srivatsamarichi** [comment]
How are the images stored in a blob container? When I upload the picture to process during booking?

**Comment by bradygmsft** [comment]
Yes, when you upload the pictures or use the pet-tester page.

**Comment by srivatsamarichi** [comment]
Okay I get it now.
