### ISSUE TITLE
deploy web.json errors out

### ISSUE THREAD

**Issue by acangialosi** [Microsoft/SmartHotel360-Website#7]
PS C:\Users\Anthony\Source\Repos\smarthotel360\SmartHotel360-public-web\arm> .\deploy.cmd .\web sh360pw-dev
Deploying ARM template '.\web.json' in resource group sh360pw-dev
Expecting ',' delimiter: line 45 column 4 (char 1238)

**Comment by dsanchezcr** [comment]
Solved with commit [eebc9b](https://github.com/Microsoft/SmartHotel360-Website/commit/eebc9b11274c812474cb763f27a9e99e222435e0url). Thanks!
