### ISSUE TITLE
Build error in vs for mac

### ISSUE THREAD

**Issue by zj2050** [Microsoft/SmartHotel360-Website#8]
when build smarthotel360 web in vs for mac , hint error  :  Error MSB3073: The command "node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js" exited with code 1.

SmartHotel360web/SmartHotel360.PublicWeb/EXEC: Error: Cannot find module 'SmartHotel360web/SmartHotel360.PublicWeb/node_modules/webpack/bin/webpack.js' (SmartHotel360.PublicWeb)

docker and nodejs all installed and docker is running

**Comment by bradygmsft** [comment]
@zj2050 this is by design, unfortunately! We created this demo to show certain features that exist in VS that aren't yet in VS4M. That said, i'd like to inquire with @eiximenis if he thinks this could be done. I'd personally love to see this happen.
